display_name: RostovVPN
publisher_display_name: "Pivovarov Co"
identity_name: PivovarovCo.RostovVPN
msix_version: 2.7.5.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: en-us, zh-cn, zh-tw, tr-tr,fa-ir,ru-ru,pt-br,es-es
protocol_activation: rostovvpn
execution_alias: rostovvpn
certificate_path: windows\sign.pfx
certificate_password:
publisher: CN=8CBDD519-B428-4491-807F-AB43C1E04102
install_certificate: "false"
enable_at_startup: "true"
startup_task:
  parameters: --autostart