display_name: RostovVPN
url: https://rostovvpn.run.place
license: Other

packager: rostovvpn
packagerEmail: linux@rostovvpn.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/source/ic_launcher_border.png

keywords:
  - RostovVPN
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: RostovVPN

group: Applications/Internet

startup_notify: true
