#!/bin/bash

cd "$(dirname "$0")"
export LD_LIBRARY_PATH=usr/lib

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} ...
start RostovVPN or RostovVPNCli, when no parameter is given, RostovVPN is executed.
    -v              show version
EOF
}
show_version() {
    printf "RostovVPN version "
    jq .version <./data/flutter_assets/version.json
}
# Initialize variables:
service=0 #declare -i service
OPTIND=1

# Resetting OPTIND is necessary if getopts was used previously in the script.
# It is a good idea to make OPTIND local if you process options in a function.

# if no arg is provided, execute rostovVPN app
if [[ $# == 0 ]];then 
    exec ./RostovVPN
else

# processing arguments

    case $1 in
        RostovVPNCli)  
            exec ./RostovVPNCli ${@:3}
            exit 0
            ;;
        h)
            show_help
            exit 0
            ;;
        v)  show_version
            exit 0
            ;;
        *)
            show_help >&2
            exit 1
            ;;
    esac



fi
