display_name: RostovVPN
package_name: rostovvpn
maintainer:
  name: rostovvpn
  email: linux@rostovvpn.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/source/ic_launcher_border.png

postinstall_scripts:
  - echo "Installed RostovVPN"
postuninstall_scripts:
  - echo "Surprised Why?"

keywords:
  - RostovVPN
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: RostovVPN

categories:
  - Network

startup_notify: true
